<a href="https://colab.research.google.com/github/HalyshAnton/IT-Step-Pyton-AI/blob/main/module2/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Аналіз даних


**Матеріали**:

-   Корисні матеріали по numpy із зображеннями [A Visual Intro to NumPy](http://jalammar.github.io/visual-numpy/).


## Numpy

Numpy це модуль мови Python для швидких математичних обчислень. Він дозволяє створювати та обробляти масиви даних високих розмірностей.

Щоб використовувати `numpy`, нам спочатку потрібно імпортувати пакет numpy. За домовленістю ми імпортуємо його за допомогою псевдоніма `np`. Тоді, коли ми хочемо використовувати модулі або функції в цій бібліотеці, ми перед ними ставимо `np`.

In [2]:
import numpy as np

### Масиви

Масив numpy — це сітка однотипних значень. Кожен елемент індексується декількома числами, в залежності від розмірності масиву.

Створення на основі списків

In [3]:
a = np.array([1, 2, 3])  # одновимірний масив



![](http://jalammar.github.io/images/numpy/create-numpy-array-1.png)

In [4]:
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


Можна створювати масиви багатьох розмірностей

![](http://jalammar.github.io/images/numpy/numpy-array-create-2d.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array.png)

In [5]:
b = np.array([[1,2],[3,4]])   # двовимірний масив
print(b)

[[1 2]
 [3 4]]


In [6]:
print(b.shape)

(2, 2)


Часто бувають випадки, коли ми хочемо, щоб numpy ініціалізував для нас значення масиву. numpy надає такі методи, як `ones()`, `zeros()` і `random.random()` для цих випадків. Ми просто передаємо їм ту кількість елементів, яку ми хочемо створити

![](http://jalammar.github.io/images/numpy/create-numpy-array-ones-zeros-random.png)

Ми також можемо використовувати ці методи для створення багатовимірних масивів, якщо ми передаємо їм кортеж, що описує розміри матриці, яку ми хочемо створити:

![](http://jalammar.github.io/images/numpy/numpy-matrix-ones-zeros-random.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array-creation.png)

In [7]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [8]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [9]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [10]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [11]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.339443   0.69049703]
 [0.43957987 0.10161486]]


Нарешті, я хочу згадати дві дуже корисні функції для створення послідовностей чисел у визначеному діапазоні, а саме `arange` і `linspace`. Функція arange у NumPy має той самий синтаксис, що й об’єкти `range` в Python: якщо надано два аргументи, перший аргумент представляє початкове значення, а друге значення визначає кінцеве значення напіввідкритого інтервалу:

Numpy також має дві корисні функції для створення послідовностей чисел: `arange` і `linspace`.

Функція `arange` приймає три аргументи, які визначають початкове значення, кінцеве значення(яке на включається) інтервалу та розмір кроку. (Розмір кроку за замовчуванням, якщо не вказано явно, дорівнює 1; початкове значення за замовчуванням, якщо не вказано явно, дорівнює 0.)

Функція `linspace` схожа, але ми можемо вказати кількість значень замість розміру кроку, і вона створить послідовність рівномірно розташованих значень.

In [12]:
f = np.arange(10,50,5)   # Create an array of values starting at 10 in increments of 5
print(f)

[10 15 20 25 30 35 40 45]


In [13]:
g = np.linspace(0., 1., num=5)
print(g)

[0.   0.25 0.5  0.75 1.  ]


Іноді ми можемо захотіти побудувати масив із існуючих масивів, «складаючи» існуючі масиви вертикально або горизонтально. Ми можемо використовувати `vstack()` (або `row_stack`) і `hstack()` (або `column_stack`), відповідно.

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f"{a=}\n")
print(f"{b=}\n")
np.vstack((a,b))

a=array([1, 2, 3])

b=array([4, 5, 6])



array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a = np.array([[7], [8], [9]])
b = np.array([[4], [5], [6]])

print(f"{a=}\n")
print(f"{b=}\n")
np.hstack((a,b))

a=array([[7],
       [8],
       [9]])

b=array([[4],
       [5],
       [6]])



array([[7, 4],
       [8, 5],
       [9, 6]])

### Індекси


Numpy пропонує кілька способів індексування в масиви.

Ми можемо індексувати та використовувати розділення `slice` для масивів numpy усіма способами, як зі списками Python:

![](http://jalammar.github.io/images/numpy/numpy-array-slice.png)

І ви можете індексувати та розділяти масиви numpy у кількох вимірах. Якщо розрізати масив із кількома вимірами, ви повинні вказати зріз для кожного виміру:

![](http://jalammar.github.io/images/numpy/numpy-matrix-indexing.png)

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

Фрагмент масиву — це перегляд тих самих даних, тому його зміна призведе до зміни оригінального масиву.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

Ви також можете поєднувати цілі індекси з індексуванням фрагментів. Однак це призведе до масиву нижчого виміру, ніж вихідний масив.

In [20]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Два способи доступу до даних у другому рядку масиву. Змішування цілочисельної індексації з фрагментами дає масив нижчого рангу, тоді як використання лише фрагментів дає масив того самого рангу, що й вихідний масив:

In [22]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [24]:
# Для стовпчиків
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


Індексування цілочисельного масиву: коли ви індексуєте масиви numpy за допомогою слайсів, отриманий масив завжди буде підмасивом вихідного масиву. Навпаки, індексація цілочисельного масиву дозволяє створювати довільні масиви, використовуючи дані з іншого масиву.

In [26]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print()

# An example of integer array indexing.
# Результатом є масив розміру (3,)
print(a[[0, 1, 2], [0, 1, 0]])
print()

# Даний рялок коду аналогічний наступному
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[[1 2]
 [3 4]
 [5 6]]

[1 4 5]
[1 4 5]


Отримані таким чином елементи можна змінювати у вихідному масиві

In [32]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[range(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [34]:
# Mutate one element from each row of a using the indices in b
a[range(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Логічне індексування масиву: логічне індексування масиву дозволяє вибирати довільні елементи масиву. Часто цей тип індексування використовується для вибору елементів масиву, які задовольняють певну умову.

In [35]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # знайти елементи які більше 2;
                    # поверне масив з True/False такого ж розміру як а
                    # де кожен елемент bool_idx каже
                    # чи виконується умова для відповідного елемента в а

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# Використання логічного індексування поверне одновимірний масив
# з елементами які відповідають True

print(a[bool_idx])

# В одному рядку коду
print(a[a > 2])

Під час роботи з масивами numpy часто корисно отримати *індекси* (а не лише значення) елементів масиву, які відповідають певним умовам. Є кілька функцій numpy, які ви точно захочете запам’ятати:

-   [`argmax`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) (індекс максимального елементу)
-   [`argmin`](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) (індекс мінімального елементу)
-   [`argsort`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) (відсортований список індексів за значенням елемента в порядку зростання)
-   [`where`](https://numpy.org/doc/stable/reference/generated/numpy.where.html) (індекси елементів, які відповідають певній умові)

In [37]:
a = np.array([1, 8, 9, -3, 2, 4, 7, 9])

print(np.argmax(a))

print(np.argmin(a))

print(np.argsort(a))

print(np.argsort(a)[::-1])

print(np.where(a > 5)[0])

2
3
[3 0 4 5 6 1 2 7]
[7 2 1 6 5 4 0 3]
[1 2 6 7]


Більше інформації у документації

### Типи даних

Кожен масив numpy є сіткою елементів одного типу. Numpy надає великий набір числових типів даних, які можна використовувати для створення масивів. Numpy намагається вгадати тип даних, коли ви створюєте масив, але функції, які створюють масиви, зазвичай також включають необов’язковий аргумент для явного визначення типу даних.

In [38]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


Більше тут [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Дії з масивами

Що робить роботу з `numpy` такою потужною та зручною, так це те, що він містить багато *векторизованих* математичних функцій для обчислень над елементами масиву. Ці функції дуже оптимізовані та *дуже* швидкі - набагато, набагато швидше, ніж використання явного циклу for.

Наприклад, давайте створимо великий масив випадкових значень, а потім підсумуємо його в обох напрямках. Ми використаємо `%%time` *cell magic*, щоб визначити час.

In [42]:
a = np.random.random(10000000)

In [43]:
%%time
x = np.sum(a)

CPU times: user 10.5 ms, sys: 0 ns, total: 10.5 ms
Wall time: 22.7 ms


In [44]:
%%time
x = 0
for element in a:
  x = x + element

CPU times: user 1.89 s, sys: 3.3 ms, total: 1.9 s
Wall time: 1.91 s


Зверніть увагу, наскільки швидша векторизована версія операції! Цей тип швидких обчислень є основним засобом машинного навчання, яке вимагає *багато* обчислень.

За можливості ми намагатимемося використовувати ці векторизовані операції.

Деякі математичні функції доступні як перевантаження операторів, так і функції в модулі numpy.


Наприклад, ви можете виконати поелементне підсумовування двох масивів за допомогою оператора + або функції `add()`.

![](http://jalammar.github.io/images/numpy/numpy-arrays-adding-1.png)

![](http://jalammar.github.io/images/numpy/numpy-matrix-arithmetic.png)

In [45]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


І це також працює для інших операцій, а не лише для додавання:

![](http://jalammar.github.io/images/numpy/numpy-array-subtract-multiply-divide.png)

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Можна використовуємо функцію `dot()` для обчислення скалярних добутків векторів, множення вектора на матрицю та множення матриць. `dot()` доступний і як функція в модулі numpy, і як метод екземпляра об’єктів масиву:

Корисне посилання: ![Matrix maltuplication](http://www.mathsisfun.com/algebra/matrix-multiplying.html)

![](http://jalammar.github.io/images/numpy/numpy-matrix-dot-product-1.png)

In [46]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


Ви також можете використовувати оператор `@`, який еквівалентний функції `dot` numpy.

In [47]:
print(v @ w)

219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [52]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x, "\n")
print(y, "\n")
print(x @ y, "\n")

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[19 22]
 [43 50]] 



Окрім функцій, які перевантажують оператори, Numpy також надає багато корисних функцій для виконання обчислень у масивах, таких як `min()`, `max()`, `sum()` та інші:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-1.png)

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])

print(np.max(x))  # Compute max of all elements; prints "6"
print(np.min(x))  # Compute min of all elements; prints "1"
print(np.sum(x))  # Compute sum of all elements; prints "21"

Ми можемо застосовувати ці функції не тільки по всіх значеннях в матриці, але застосовувати їх по рядках або стовпцях за допомогою параметра `axis`:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-4.png)

In [ ]:
x = np.array([[1, 2], [5, 3], [4, 6]])

print(np.max(x, axis=0))  # Compute max of each column; prints "[5 6]"
print(np.max(x, axis=1))  # Compute max of each row; prints "[2 5 6]"

Ви можете знайти повний список математичних функцій, які надає numpy, у [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Окрім обчислення математичних функцій за допомогою масивів, нам часто потрібно змінювати форму або іншим чином маніпулювати даними в масивах. Найпростішим прикладом цього типу операції є транспонування матриці; щоб транспонувати матрицю, просто використовуйте атрибут T об’єкта масиву.

![](http://jalammar.github.io/images/numpy/numpy-transpose.png)

In [53]:
x = np.array([[1, 2], [3, 4], [5, 6]])

print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]
 [5 6]]
transpose
 [[1 3 5]
 [2 4 6]]


In [54]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


У більш просунутому випадку використання вам може знадобитися змінити розміри певної матриці. Це часто буває в програмах машинного навчання, де певна модель очікує певної форми для вхідних даних, яка відрізняється від вашого набору даних. Метод numpy `reshape()` корисний у цих випадках.

![](http://jalammar.github.io/images/numpy/numpy-reshape.png)

A common task in this class will be to convert a 1D array to a 2D array, and vice versa. We can use `reshape()` for this.

For example, suppose we had this 2D array, but we need to pass it to a function that expects a 1D array.

In [ ]:
w = np.array([[1],[2],[3]])
print(w)
w.shape

We can remove the “unnecessary” extra dimension with

In [ ]:
y = w.reshape(-1,)
print(y)
y.shape

Note that we can pass -1 as one dimension and numpy will infer the correct size based on our matrix size!

There’s also a `squeeze()` function that removes *all* of the “unnecessary” dimensions (dimensions that have size 1) from an array:

In [ ]:
z = w.squeeze()
print(z)
z.shape

To go from a 1D to 2D array, we can just add in another dimension of size 1:

In [ ]:
y.reshape((-1,1))

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.

For example: basic linear algebra, we can only add (and perform similar element-wise operations) two matrics that have the *same* dimension. In numpy, if we want to add two matrics that have different dimensions, numpy will implicitly “extend” the dimension of one matrix to match the other so that we can perform the operation.

So these operations will work, instead of returning an error:

![](https://sebastianraschka.com/images/blog/2020/numpy-intro/broadcasting-1.png)

![](https://sebastianraschka.com/images/blog/2020/numpy-intro/broadcasting-2.png)

Broadcasting two arrays together follows these rules:

**Rule 1**: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

For example, in the following cell, `a` will be implicitly extended to shape (1,3):

In [ ]:
a = np.array([1,2,3])         # has shape (3,): one dimension
b = np.array([[4], [5], [6]]) # has shape (3,1): two dimensions
c = a + b                     # will have shape (3,3) (two dimensions)

**Rule 2**: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

For example, in the following cell `a` will be implicitly extended to shape (3,2):

In [ ]:
a = np.array([[1],[2],[3]])         # has shape (3,1)
b = np.array([[4,5], [6,7], [8,9]]) # has shape (3,2)
c = a + b                           # will have shape (3,2)

**Rule 3**: If in any dimension the sizes disagree and neither is equal to 1, an error is raised:

In [ ]:
a = np.array([[1],[2],[3],[4]])      # has shape (4,1)
b = np.array([[4,5], [6,7], [8,9]])  # has shape (3,2)
c = a + b                            # ValueError: operands could not be broadcast

For more detail, you can read the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are a few visual examples involving broadcasting.

![](http://jalammar.github.io/images/numpy/numpy-array-broadcast.png)

Note that these arrays are compatible in each dimension if they have either the same size in that dimension, or if one array has size 1 in that dimension.

![](http://jalammar.github.io/images/numpy/numpy-matrix-broadcast.png)

And here are some more practical applications:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

## Matplotlib

Matplotlib is a plotting library. In this section we give a brief introduction to the `matplotlib.pyplot` module, which provides a plotting system similar to that of MATLAB.

By convention, we typically import this module using the `plt` alias:

In [ ]:
import matplotlib.pyplot as plt

### Plotting

The most important function in `matplotlib` is `plot`, which allows you to plot 2D data as a line plot. Here is a simple example:

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)

# Show the figure.
plt.show()

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin, label='Sine')
plt.plot(x, y_cos, label='Cosine')
plt.legend() # uses the label arguments given above

plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')

# Show the figure.
plt.show()

Another useful, basic, plot is the `scatter` plot:

In [ ]:
x = np.random.rand(50)
y = np.random.rand(50)
colors = np.random.randint(0, 2, 50)

plt.scatter(x, y, c=colors)

plt.show()

When there is no logical connection between adjacent points (for example: if the horizontal axis is a categorical variable without a logical order), then you should *not* connect them (as in a line plot), since this implies a relationship that does not exist! Instead, you would use a scatter plot.

### Subplots

You can plot different things in the same figure using the `subplot` function. Here is an example:

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Adjust spacing between subplots
plt.subplots_adjust(hspace = 0.4)

# Show the figure.
plt.show()

You can read much more about the `subplot` function in the [documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).

You can use the `imshow` function to display images from a file. Here is an example:

In [ ]:
from matplotlib.cbook import get_sample_data

img_file = get_sample_data('grace_hopper.jpg')

img = plt.imread(img_file)
plt.imshow(img)
plt.show()

The `matplotlib` library is very flexible, and you can create virtually any plot and modify its appearance in any way you might think of. If you don’t like the way your plot looks, fix it! Use the [documentation](http://matplotlib.org/api/pyplot_api.html) to learn more.